services:
  rabbitmq-service:
    image: docker.io/rabbitmq:management
    container_name: rabbitmq-service
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.docker/rabbitmq_init.sh:/rabbitmq_init.sh
    command: [ "bash", "-c", "/rabbitmq_init.sh" ]

  valkey-service:
    image: "docker.io/valkey/valkey:alpine"
    container_name: valkey
    command:
      - /bin/sh
      - -c
      - valkey-server --requirepass "$${VALKEY_PASSWORD}"
    ports:
      - "6379:6379"
    environment:
      VALKEY_REPLICATION_MODE: "master"
      VALKEY_PASSWORD: "${VALKEY_PASSWORD}"

  db:
    image: postgres:17-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-template_app_db}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-dev}"
      POSTGRES_USER: "${POSTGRES_USER:-dev}"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${DATABASE_NAME}",
          "-U",
          "${DATABASE_USER}",
        ]
      start_period: 3s
      interval: 5s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-dev}:${POSTGRES_PASSWORD:-dev}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-template_app_db}?sslmode=disable"
    entrypoint: /bin/bash
    command: [
      "-c",
      "until pg_isready -h ${POSTGRES_HOST:-db} -d ${POSTGRES_DB:-template_app_db}; do echo 'wait for db'; sleep 1; done && pgweb --bind=0.0.0.0"
    ]
    depends_on:
      db:
        condition: service_healthy

  fastapi-template-migrate:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fastapi-template-service
    container_name: fastapi-template-migrate
    environment:
      DB_DSN: "postgresql+asyncpg://${POSTGRES_USER:-dev}:${POSTGRES_PASSWORD:-dev}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-template_app_db}"
      LOGGING_LEVEL: "${LOGGING_LEVEL:-DEBUG}"
    entrypoint: python3
    command: ["-m", "alembic", "upgrade", "head"]
    depends_on:
      db:
        condition: service_healthy

  fastapi-template-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fastapi-template-service
    container_name: fastapi-template-service
    ports:
      - "8080:8080"
    environment:
      AMQP_DSN: "${AMQP_DSN:-amqp://guest:guest@rabbitmq-service/}"
      DB_DSN: "postgresql://${POSTGRES_USER:-dev}:${POSTGRES_PASSWORD:-dev}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-template_app_db}"
      LOGGING_LEVEL: "${LOGGING_LEVEL:-DEBUG}"
    depends_on:
      - db
      - rabbitmq-service
      - valkey-service
      - fastapi-template-migrate
