apiVersion: v1
kind: Secret
metadata:
  name: dockerregistrycreds-hook
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
