apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
spec:
  compress:
    defaultEncoding: gzip
    encodings:
      - gzip
    includedContentTypes:
      - application/javascript
      - application/json
      - text/css
      - text/html
      - text/plain
{{/*---*/}}
{{/*apiVersion: traefik.io/v1alpha1*/}}
{{/*kind: Middleware*/}}
{{/*metadata:*/}}
{{/*  name: ratelimit*/}}
{{/*spec:*/}}
{{/*  rateLimit:*/}}
{{/*    average: 3*/}}
{{/*    burst: 5*/}}
{{/*    period: 1s*/}}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers
spec:
  headers:
    forceSTSHeader: true
    stsSeconds: 31536000              # 1 year
    stsIncludeSubdomains: true
    stsPreload: true
    browserXssFilter: true
    contentTypeNosniff: true
    frameDeny: true
    permissionsPolicy: >
      accelerometer=(),
      autoplay=(),
      camera=(),
      clipboard-read=(),
      clipboard-write=(),
      geolocation=(),
      gyroscope=(),
      magnetometer=(),
      microphone=(),
      payment=(),
      usb=()
    customResponseHeaders:
      X-Powered-By: ""
