apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-project-template.fullname" . }}-db
  labels:
    {{- include "fastapi-project-template.db.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "fastapi-project-template.db.selectorLabels" . | nindent 4 }}
---
{{- if .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fastapi-project-template.fullname" . }}-db
  labels:
    {{- include "fastapi-project-template.db.selectorLabels" . | nindent 4 }}
spec:
  accessModes: {{ toYaml .Values.postgresql.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-project-template.fullname" . }}-db
  labels:
    {{- include "fastapi-project-template.db.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fastapi-project-template.db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fastapi-project-template.db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password | quote }}
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgresql.username | quote }}
                - -d
                - {{ .Values.postgresql.database | quote }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgresql.username | quote }}
                - -d
                - {{ .Values.postgresql.database | quote }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/18
      volumes:
        - name: pgdata
{{- if .Values.postgresql.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "fastapi-project-template.fullname" . }}-db
{{- else }}
          emptyDir: { }
{{- end }}
